[backend/att]: An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/router.py", line 127, in _start_backend
    started = backend.start()
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/backends/gsm.py", line 167, in start
    BackendBase.start(self)
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/backends/base.py", line 51, in start
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/backends/gsm.py", line 132, in run
    msg = self.modem.next_message()
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 568, in next_message
    self._fetch_stored_messages()
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 545, in _fetch_stored_messages
    lines = self.command('AT+CMGL=%s' % self.smshandler.CMGL_STATUS)
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 375, in command
    raise(err)
GsmReadTimeoutError
[router]: waiting 15 seconds before retrying
[router]: Caught KeyboardInterrupt
[router]: Stopping...
[backend/att]: debug: Disconnecting
[router]: returning from _start_backend
[router]: backend <backend: message_tester> terminated normally
[router]: Stopped
[django.db.backends]: (0.001) SELECT `rapidsms_backend`.`name` FROM `rapidsms_backend`; args=()
[django.db.backends]: (0.001) SELECT `rapidsms_app`.`module` FROM `rapidsms_app`; args=()
[router]: Starting RapidSMS...
[router]: starting backend
[backend/att]: Connecting and booting via pyGSM...
[router]: starting backend
[app/handlers]: Registered: EchoHandler, PingHandler
[backend/att]: debug: Booting
[backend/att]: debug: Connecting
[app/ajax]: An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/router.py", line 195, in _start_all_apps
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/contrib/ajax/app.py", line 214, in start
    self.RequestHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 408, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
[router]: Started
[backend/att]: write: 'ATE0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMEE=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+WIND=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'ERROR\r\n'
[backend/att]: write: 'AT+CSMS=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CSMS: 1,1,1\r\n'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGF=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CNMI=2,2,0,0,0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CMS ERROR: 303\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: debug: Booting
[backend/att]: debug: Connecting
[backend/att]: write: 'ATE0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMEE=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+WIND=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'ERROR\r\n'
[backend/att]: write: 'AT+CSMS=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CSMS: 1,1,1\r\n'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGF=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CNMI=2,2,0,0,0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CMS ERROR: 303\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: Polling modem for messages
[backend/att]: write: 'AT\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: debug: Disconnecting
[router]: caught exception in backend pyGSM: 
[backend/att]: An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/router.py", line 127, in _start_backend
    started = backend.start()
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/backends/gsm.py", line 167, in start
    BackendBase.start(self)
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/backends/base.py", line 51, in start
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/backends/gsm.py", line 132, in run
    msg = self.modem.next_message()
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 568, in next_message
    self._fetch_stored_messages()
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 545, in _fetch_stored_messages
    lines = self.command('AT+CMGL=%s' % self.smshandler.CMGL_STATUS)
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 375, in command
    raise(err)
GsmReadTimeoutError
[router]: waiting 15 seconds before retrying
[router]: starting backend
[backend/att]: Connecting and booting via pyGSM...
[backend/att]: debug: Booting
[backend/att]: debug: Connecting
[backend/att]: write: 'ATE0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMEE=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+WIND=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'ERROR\r\n'
[backend/att]: write: 'AT+CSMS=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CSMS: 1,1,1\r\n'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGF=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CNMI=2,2,0,0,0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CMS ERROR: 303\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: debug: Booting
[backend/att]: debug: Connecting
[backend/att]: write: 'ATE0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMEE=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+WIND=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'ERROR\r\n'
[backend/att]: write: 'AT+CSMS=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CSMS: 1,1,1\r\n'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGF=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CNMI=2,2,0,0,0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CMS ERROR: 303\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: Polling modem for messages
[backend/att]: write: 'AT\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: debug: Disconnecting
[router]: caught exception in backend pyGSM: 
